#!/usr/bin/env bash
# I have modified the script to work with ligh(arch package) to control brightness as xbacklight didn't work without package 'xf86-video-intel' which causes my 
# to freeze quite often

#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


STEP_SIZE=${STEP_SIZE:-5}
USE_SUDO=${USE_SUDO:-0}

# whether to use `sudo` for changing the brightness (requires a NOPASSWD rule)
if [[ "$USE_SUDO" == "0" ]] ; then
    LIGHT_SET="light"
else
    LIGHT_SET="sudo light"
fi

case $BLOCK_BUTTON in
  3) xset dpms force off ;; # right click
  4) $LIGHT_SET -inc "$STEP_SIZE" ;; # scroll up
  5) $LIGHT_SET -dec "$STEP_SIZE" ;; # scroll down, decrease
esac


BRIGHTNESS=$(light -get)
echo "${BRIGHTNESS}%"
